package jp.example.repository;

import java.util.List;
import jp.example.dto.Attachement;
import jp.example.dto.AttachementExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AttachementMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.attachement
     * @mbg.generated
     */
    long countByExample(AttachementExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.attachement
     * @mbg.generated
     */
    int deleteByExample(AttachementExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.attachement
     * @mbg.generated
     */
    int insert(Attachement record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.attachement
     * @mbg.generated
     */
    int insertSelective(Attachement record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.attachement
     * @mbg.generated
     */
    List<Attachement> selectByExampleWithBLOBsWithRowbounds(AttachementExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.attachement
     * @mbg.generated
     */
    List<Attachement> selectByExampleWithBLOBs(AttachementExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.attachement
     * @mbg.generated
     */
    List<Attachement> selectByExampleWithRowbounds(AttachementExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.attachement
     * @mbg.generated
     */
    List<Attachement> selectByExample(AttachementExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.attachement
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Attachement record, @Param("example") AttachementExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.attachement
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Attachement record, @Param("example") AttachementExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table public.attachement
     * @mbg.generated
     */
    int updateByExample(@Param("record") Attachement record, @Param("example") AttachementExample example);
}