package jp.example.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.example.dto.Mail;
import jp.example.dto.MailExample;

public interface MailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mail
     *
     * @mbg.generated
     */
    long countByExample(MailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mail
     *
     * @mbg.generated
     */
    int deleteByExample(MailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mail
     *
     * @mbg.generated
     */
    int insert(Mail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mail
     *
     * @mbg.generated
     */
    int insertSelective(Mail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mail
     *
     * @mbg.generated
     */
    List<Mail> selectByExampleWithRowbounds(MailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mail
     *
     * @mbg.generated
     */
    List<Mail> selectByExample(MailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Mail record, @Param("example") MailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.mail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Mail record, @Param("example") MailExample example);

    Mail selectMail(@Param("id") String id);
}
