package jp.example.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.attachement
 */
public class Attachement {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column public.attachement.id
     * @mbg.generated
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column public.attachement.filename
     * @mbg.generated
     */
    private String filename;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column public.attachement.attachement
     * @mbg.generated
     */
    private byte[] attachement;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.attachement.id
     * @return  the value of public.attachement.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.attachement.id
     * @param id  the value for public.attachement.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.attachement.filename
     * @return  the value of public.attachement.filename
     * @mbg.generated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.attachement.filename
     * @param filename  the value for public.attachement.filename
     * @mbg.generated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column public.attachement.attachement
     * @return  the value of public.attachement.attachement
     * @mbg.generated
     */
    public byte[] getAttachement() {
        return attachement;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column public.attachement.attachement
     * @param attachement  the value for public.attachement.attachement
     * @mbg.generated
     */
    public void setAttachement(byte[] attachement) {
        this.attachement = attachement;
    }
}